version: '3.8'

services:
  backend:
    build: ./backend
    container_name: node-auth-backend
    ports:
      - "5000:5000"
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: react-auth-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: mysql:5.7
    container_name: mysql-auth-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: auth_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
